namespace AppTradingAlgoritmico.Application.DTOs.Strategies;

public record StrategyDto(
    Guid Id,
    string Name,
    string? Pseudocode,
    // Indicator metadata
    string? EntryIndicators,
    string? PriceIndicators,
    string? IndicatorParameters,
    // Backtest metadata
    string? Symbol,
    string? Timeframe,
    DateTime? BacktestFrom,
    DateTime? BacktestTo,
    // Summary: top-left
    decimal? TotalProfit,
    decimal? ProfitInPips,
    decimal? YearlyAvgProfit,
    decimal? YearlyAvgReturn,
    decimal? Cagr,
    // Summary: grid
    int? NumberOfTrades,
    decimal? SharpeRatio,
    decimal? ProfitFactor,
    decimal? ReturnDrawdownRatio,
    decimal? WinningPercentage,
    decimal? Drawdown,
    decimal? DrawdownPercent,
    decimal? DailyAvgProfit,
    decimal? MonthlyAvgProfit,
    decimal? AverageTrade,
    decimal? AnnualReturnMaxDdRatio,
    decimal? RExpectancy,
    decimal? RExpectancyScore,
    decimal? StrQualityNumber,
    decimal? SqnScore,
    // Stats: Strategy
    decimal? WinsLossesRatio,
    decimal? PayoutRatio,
    decimal? AverageBarsInTrade,
    decimal? Ahpr,
    decimal? ZScore,
    decimal? ZProbability,
    decimal? Expectancy,
    decimal? Deviation,
    decimal? Exposure,
    int? StagnationInDays,
    decimal? StagnationPercent,
    // Stats: Trades
    int? NumberOfWins,
    int? NumberOfLosses,
    int? NumberOfCancelled,
    decimal? GrossProfit,
    decimal? GrossLoss,
    decimal? AverageWin,
    decimal? AverageLoss,
    decimal? LargestWin,
    decimal? LargestLoss,
    int? MaxConsecutiveWins,
    int? MaxConsecutiveLosses,
    decimal? AverageConsecutiveWins,
    decimal? AverageConsecutiveLosses,
    decimal? AverageBarsInWins,
    decimal? AverageBarsInLosses,
    DateTime CreatedAt
);
